paths:
  /products:
    get:
      summary: Obtener productos con opciones de filtrado.
      tags:
        - Products
      parameters:
        - in: query
          name: limit
          type: integer
          description: Número máximo de productos a retornar.
        - in: query
          name: page
          type: integer
          description: Número de página.
        - in: query
          name: sort
          type: string
          enum: ['asc', 'desc']
          description: Orden de clasificación (ascendente o descendente).
        - in: query
          name: query
          type: string
          description: Categoría de productos a filtrar.
        - in: query
          name: minPrice
          type: number
          description: Precio mínimo de los productos a filtrar.
        - in: query
          name: maxPrice
          type: number
          description: Precio máximo de los productos a filtrar.
      responses:
        '200':
          description: Lista de productos paginada.
          content:
            application/json:
              example: 
                productos: []
                pagination:
                  totalDocs: 0
                  totalPages: 0
                  page: 1
                  limit: 10
                  hasPrevPage: false
                  hasNextPage: false
          schema:
            type: object
            properties:
              productos:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              pagination:
                $ref: '#/components/schemas/Pagination'
        '400':
          description: Error en la solicitud. Puede deberse a parámetros incorrectos.
          content:
            application/json:
              example:
                mensaje: 'Error en la solicitud. Parámetros incorrectos.'
        '401':
          description: No autorizado. El usuario debe iniciar sesión.
          content:
            application/json:
              example:
                mensaje: 'No autorizado. El usuario debe iniciar sesión.'
        '500':
          description: Error en el servidor. Consulta el registro de errores para más detalles.
          content:
            application/json:
              example:
                mensaje: 'Error en el servidor.'
                error: 'Descripción detallada del error.'
    post:
      summary: Crear un nuevo producto.
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            example:
              nombre: "Nombre del Producto"
              descripcion: "Descripción del producto."
              precio: 29.99
              categoria: "Electrónicos"
              imagen: "url_de_la_imagen.jpg"
              disponibilidad: true
          schema:
            $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Producto creado con éxito.
          content:
            application/json:
              example:
                mensaje: 'Producto creado con éxito.'
        '400':
          description: Error en la solicitud. Puede deberse a datos incorrectos.
          content:
            application/json:
              example:
                mensaje: 'Error en la solicitud. Datos incorrectos.'
        '401':
          description: No autorizado. El usuario debe iniciar sesión.
          content:
            application/json:
              example:
                mensaje: 'No autorizado. El usuario debe iniciar sesión.'
        '500':
          description: Error en el servidor. Consulta el registro de errores para más detalles.
          content:
            application/json:
              example:
                mensaje: 'Error en el servidor.'
                error: 'Descripción detallada del error.'

  /product/{_id}:
    get:
      summary: Obtener detalles de un producto.
      tags:
        - Products
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
          description: ID del producto para obtener detalles.
      responses:
        '200':
          description: Detalles del producto.
          content:
            application/json:
              example:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado.
          content:
            application/json:
              example:
                mensaje: 'Producto no encontrado.'
        '500':
          description: Error en el servidor al intentar obtener detalles del producto.
          content:
            application/json:
              example:
                mensaje: 'Error en el servidor al intentar obtener detalles del producto.'
                error: 'Descripción detallada del error.'
    put:
      summary: Actualizar detalles de un producto.
      tags:
        - Products
      parameters:
        - in: path
          name: _id
          required: true
          schema:
            type: string
          description: ID del producto a actualizar.
      requestBody:
        required: true
        content:
          application/json:
            example:
              nombre: "Nuevo Nombre"
              descripcion: "Nueva Descripción"
              precio: 39.99
              categoria: "Electrónicos"
              imagen: "nueva_url_de_la_imagen.jpg"
              disponibilidad: false
          schema:
            $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado con éxito.
          content:
            application/json:
              example:
                mensaje: 'Producto actualizado con éxito.'
        '400':
          description: Error en la solicitud. Puede deberse a datos incorrectos.
          content:
            application/json:
              example:
                mensaje: 'Error en la solicitud. Datos incorrectos.'
        '401':
          description: No autorizado. El usuario debe iniciar sesión.
          content:
            application/json:
              example:
                mensaje: 'No autorizado. El usuario debe iniciar sesión.'
        '404':
          description: Producto no encontrado.
          content:
            application/json:
              example:
                mensaje: 'Producto no encontrado.'
        '500':
          description: Error en el servidor. Consulta el registro de errores para más detalles.
          content:
            application/json:
              example:
                mensaje: 'Error en el servidor.'
                error: 'Descripción detallada del error.'
  /product/add:
      get:
        summary: Mostrar la página para agregar un nuevo producto.
        tags:
          - Products
        responses:
          '200':
            description: Página de agregar producto renderizada con éxito.
            content:
              text/html:
                example: Página de agregar producto HTML
          '500':
            description: Error en el servidor al intentar mostrar la página de agregar producto.
            content:
              application/json:
                example:
                  mensaje: 'Error en el servidor al intentar mostrar la página de agregar producto.'
                  error: 'Descripción detallada del error.'
      post:
        summary: Agregar un nuevo producto.
        tags:
          - Products
        requestBody:
          required: true
          content:
            application/json:
              example:
                nombre: "Nombre del Producto"
                descripcion: "Descripción del producto."
                precio: 29.99
                categoria: "Electrónicos"
                imagen: "url_de_la_imagen.jpg"
                disponibilidad: true
            schema:
              $ref: '#/components/schemas/Product'
        responses:
          '201':
            description: Producto creado con éxito.
            content:
              application/json:
                example:
                  mensaje: 'Producto creado con éxito.'
          '400':
            description: Error en la solicitud. Puede deberse a datos incorrectos.
            content:
              application/json:
                example:
                  mensaje: 'Error en la solicitud. Datos incorrectos.'
          '401':
            description: No autorizado. El usuario debe iniciar sesión.
            content:
              application/json:
                example:
                  mensaje: 'No autorizado. El usuario debe iniciar sesión.'
          '500':
            description: Error en el servidor. Consulta el registro de errores para más detalles.
            content:
              application/json:
                example:
                  mensaje: 'Error en el servidor.'
                  error: 'Descripción detallada del error.'
  /product/edit/{id}:
      get:
        summary: Mostrar la página de edición de un producto.
        tags:
          - Products
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
            description: ID del producto a editar.
        responses:
          '200':
            description: Página de edición de producto renderizada con éxito.
            content:
              text/html:
                example: Página de edición de producto HTML
          '404':
            description: Producto no encontrado.
            content:
              application/json:
                example:
                  mensaje: 'Producto no encontrado.'
          '500':
            description: Error en el servidor al intentar mostrar la página de edición de producto.
            content:
              application/json:
                example:
                  mensaje: 'Error en el servidor al intentar mostrar la página de edición de producto.'
                  error: 'Descripción detallada del error.'
      post:
        summary: Procesar la edición de un producto.
        tags:
          - Products
        parameters:
          - in: path
            name: id
            required: true
            schema:
              type: string
            description: ID del producto a editar.
        requestBody:
          required: true
          content:
            application/json:
              example:
                nombre: "Nuevo Nombre"
                descripcion: "Nueva Descripción"
                precio: 39.99
                categoria: "Electrónicos"
                imagen: "nueva_url_de_la_imagen.jpg"
                disponibilidad: false
            schema:
              $ref: '#/components/schemas/Product'
        responses:
          '200':
            description: Producto actualizado con éxito.
            content:
              application/json:
                example:
                  mensaje: 'Producto actualizado con éxito.'
          '400':
            description: Error en la solicitud. Puede deberse a datos incorrectos.
            content:
              application/json:
                example:
                  mensaje: 'Error en la solicitud. Datos incorrectos.'
          '401':
            description: No autorizado. El usuario debe iniciar sesión.
            content:
              application/json:
                example:
                  mensaje: 'No autorizado. El usuario debe iniciar sesión.'
          '404':
            description: Producto no encontrado.
            content:
              application/json:
                example:
                  mensaje: 'Producto no encontrado.'
          '500':
            description: Error en el servidor. Consulta el registro de errores para más detalles.
            content:
              application/json:
                example:
                  mensaje: 'Error en el servidor.'
                  error: 'Descripción detallada del error.'
  /my-products:
      get:
        summary: Obtener los productos creados por el usuario.
        tags:
          - Products
        responses:
          '200':
            description: Lista de productos del usuario renderizada con éxito.
            content:
              text/html:
                example: Página de mis productos HTML
          '401':
            description: No autorizado. El usuario debe iniciar sesión.
            content:
              application/json:
                example:
                  mensaje: 'No autorizado. El usuario debe iniciar sesión.'
          '500':
            description: Error en el servidor al intentar mostrar la lista de productos del usuario.
            content:
              application/json:
                example:
                  mensaje: 'Error en el servidor al intentar mostrar la lista de productos del usuario.'
                  error: 'Descripción detallada del error.'
  /limpiar/{productId}:
      delete:
        summary: Eliminar un producto por ID.
        tags:
          - Products
        parameters:
          - in: path
            name: productId
            required: true
            schema:
              type: string
            description: ID del producto a eliminar.
        responses:
          '200':
            description: Producto eliminado con éxito.
            content:
              application/json:
                example:
                  mensaje: 'Producto eliminado con éxito.'
          '400':
            description: Error en la solicitud. Puede deberse a un ID de producto inválido.
            content:
              application/json:
                example:
                  mensaje: 'Error en la solicitud. ID de producto inválido.'
          '404':
            description: Producto no encontrado.
            content:
              application/json:
                example:
                  mensaje: 'Producto no encontrado.'
          '500':
            description: Error en el servidor al intentar eliminar el producto.
            content:
              application/json:
                example:
                  mensaje: 'Error en el servidor al intentar eliminar el producto.'
                  error: 'Descripción detallada del error.'              

# Sección de componentes para esquemas reutilizables
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        nombre:
          type: string
        descripcion:
          type: string
        precio:
          type: number
        categoria:
          type: string
        imagen:
          type: string
        disponibilidad:
          type: boolean
        createdAt:
          type: string
        stock:
          type: string

    Pagination:
      type: object
      properties:
        totalDocs:
          type: integer
        totalPages:
          type: integer
        page:
          type: integer
        limit:
          type: integer
        hasPrevPage:
          type: boolean
        hasNextPage:
          type: boolean
